# Generated by Django 5.0.6 on 2024-06-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sach',
            name='mota',
        ),
        migrations.AddField(
            model_name='sach',
            name='gioithieu',
            field=models.CharField(default='', max_length=255),
        ),
    ]
