# Generated by Django 5.0.6 on 2024-06-27 06:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_sach_mota_sach_gioithieu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sach',
            name='gioithieu',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
