# Generated by Django 5.0.6 on 2024-06-27 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_sach_gioithieu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='danhmucsach',
            name='sub_danhmuc',
        ),
        migrations.AddField(
            model_name='danhmucsach',
            name='danhmuc_con',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='danhmuc_conn', to='app.danhmucsach'),
        ),
        migrations.AlterField(
            model_name='sach',
            name='gioithieu',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
