# Generated by Django 5.0.6 on 2024-06-27 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_danhmucsach_sub_danhmuc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='danhmucsach',
            name='slug',
        ),
    ]
