# Generated by Django 5.0.6 on 2024-06-27 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_danhmucsach_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DanhMucSach',
            new_name='TheLoai',
        ),
        migrations.RenameField(
            model_name='theloai',
            old_name='tendanhmuc',
            new_name='ten_the_loai',
        ),
    ]
